name: basic_console
description: Very simple console not blocking input package, allows you to send async messages while getting user-input.
version: 1.0.0+dev.2
homepage: https://github.com/LacticWhale/dart-basic-console/

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  zekfad_lints: ^1.1.0
